class Constants(object):
  WINDOW_COLUMNS = 1280
  WINDOW_ROWS = 720

  MINIMAP_WALL = 1

  MINIMAP_COLUMNS = 198
  MINIMAP_ROWS = 196

  MIMIMAP_LOCATION_COLS = 1046
  MIMIMAP_LOCATION_ROWS = 48

  PLAYER_MINIMAP_ROW = 98
  PLAYER_MINIMAP_COLUMN = 99

  # How many seconds it takes to
  SEC_PER_PIXEL_SPEED = 0.032
  MAP_TIME_SEC = 200

  BLACK_THRESHOLD_VALUE = 44
  PLAYER_HEIGHT = 3
  PLAYER_WIDTH = 4
